### ISSUE TITLE
自动完成和zbuilder:table的callback冲突

### ISSUE THREAD

**Issue by XinJiangQingMang** [caiweiming/DolphinPHP#10]
public function setIpAttr(){
        return request()->ip();
    }
  return ZBuilder::make('table')
            ->addColumns([
                ['ip','ip地址','callback',function($value){
// 这里的$value 是获取不到值的  
                    return 456;
                }],
->fetch();

**Comment by caiweiming** [comment]
自动完成是用于写入数据的，ZBuilder::make('table')是展示数据，按道理是不会冲突的，先确认下读取出来的数据中，是否有ip字段，如果读取出来的数据没有ip字段，那么在ZBuilder::make('table')中使用setRowList（）时是不会传入ip的
