### ISSUE TITLE
config 加载调整

### ISSUE THREAD

**Issue by XinJiangQingMang** [caiweiming/DolphinPHP#12]
行为这块   默认会在  app_begin  执行 config   会导致动态配置的config 无效.

*情景是这样的  如果我后台开启了水印,但是部分上传不需要水印 我可以动态关闭 upload_thumb_water   但是执行行为以后 每次到attachment 都会重新读取配置 导致 config('upload_thumb_water',0) 无效

**Comment by caiweiming** [comment]
好的，感谢您的反馈。
