### ISSUE TITLE
你好，问个zbuild构建table时，在搜索关键字且当前页不为第1页时会搜索不到结果

### ISSUE THREAD

**Issue by nottellyou** [caiweiming/DolphinPHP#15]
你好，问个zbuild构建table时，在搜索关键字且当前页不为第1页时会搜索不到结果。

例：
使用zbuild构建当前table，翻页到第6页(大于第一页就行)，然后，搜索任何一个关键字，会搜索不到，如果将url中的page=xxx改为page=1就可以搜索 到了。

这是一个小bug吧，当进行搜索时，要将当前的page重置为1才能有结果。这个怎样处理？？？

**Comment by caiweiming** [comment]
你使用的框架版本是多少？这个bug在1.0.7以上版本修复了。

**Comment by nottellyou** [comment]
在哪里看版本？？没找到。后来我直接把curr_params清空了，现在正常了，还在查看中。
