### ISSUE TITLE
Zbuilder挺不错的，可以试下将它开源出去，让更多的人来完善它。

### ISSUE THREAD

**Issue by nottellyou** [caiweiming/DolphinPHP#16]
Zbuilder挺不错的，可以试下将它开源出去，让更多的人来完善它。

**Comment by caiweiming** [comment]
本框架一直以来就是开源的，只不过商业用户需要授权，也欢迎有兴趣的朋友提交代码。

**Comment by nottellyou** [comment]
和TP混合在一起，就不会有那么多人过来看了。

**Comment by langjihaijiao** [comment]
他的意思是，你的ZBuilder独立开源出去，你现在ZBuilder跟TP框架耦合太高了。
