### ISSUE TITLE
进入后台首页 一直302

### ISSUE THREAD

**Issue by youmikuang** [caiweiming/DolphinPHP#28]
我用的 valet 开发环境，进入后台就一直 302 跳转，表示很无语~

**Comment by snksos** [comment]
应该是你配置信息错误造成的，如果可以，贴一下你的配置，或者可以参考文档：[https://www.kancloud.cn/ming5112/dolphinphp/257920](https://www.kancloud.cn/ming5112/dolphinphp/257920)
