### ISSUE TITLE
DolphinPHP v1.5.1 has a vulnerability, Stored Cross Site Scripting(XSS)

### ISSUE THREAD

**Issue by zhangzhijie98** [caiweiming/DolphinPHP#42]
version:1.5.1
Vulnerability location:Background - > System - > system function - > configuration management.
![image](https://user-images.githubusercontent.com/60609675/181787442-07219a03-0684-4a85-bf70-12b2adc1a203.png)
![image](https://user-images.githubusercontent.com/60609675/181788265-dd1faafa-a77d-4861-8ae3-8b142e4a33a8.png)
Add a new configuration,and insert payload in the configuration title
payload: `t"><img src=x onerror=alert(1)>`
![image](https://user-images.githubusercontent.com/60609675/181788501-5f348a12-b004-4608-9db1-974956a1c268.png)
Save and refresh the page. Pop up window.
![image](https://user-images.githubusercontent.com/60609675/181788680-1a4df936-f04a-473d-bee2-35cea7938ba0.png)
payload: `<img src=x onerror=alert("xss")>`
![image](https://user-images.githubusercontent.com/60609675/181789248-a9aa23fa-e1ed-4ee1-8154-81af18daa429.png)
![image](https://user-images.githubusercontent.com/60609675/181789321-239c4cae-d838-4ff0-a09d-011b1915ee47.png)
When you visit this page, a pop-up window will pop up.

**Comment by pengge** [comment]
请考虑使用全局过滤，防止攻击，更改后需要检测业务是否存在影响。或者使用相关WAF拦截
​application\config.php 

`
'default_filter'         => 'htmlspecialchars,addslashes,strip_tags',
`
