### ISSUE TITLE
DolphinPHP v1.5.1 vulnerability, Reflected Cross Site Scripting(XSS)

### ISSUE THREAD

**Issue by zhangzhijie98** [caiweiming/DolphinPHP#43]
version:1.5.1
Vulnerability location:Background - > System - > system function - > Attachment management.
                                   Background - > System - > system function - > system log.
                                   Background - > System - > system function - > Behavior management.
![image](https://user-images.githubusercontent.com/60609675/181791503-14dcdb28-647a-40e1-967f-b8d8c8bdfa3c.png)
![image](https://user-images.githubusercontent.com/60609675/181791554-2293f9be-609c-453d-bafd-0c99eb9720b6.png)
Influence parameters:search_field
payload:`test"><img src=x onerror=alert("xss")>`
![image](https://user-images.githubusercontent.com/60609675/181791754-3eb12dcb-3d2b-45a1-ba71-dce330171156.png)
![image](https://user-images.githubusercontent.com/60609675/181791885-c642ebc6-024a-48d5-9803-4448ded06d6b.png)

**Comment by pengge** [comment]
请考虑使用全局过滤，防止攻击，更改后需要检测业务是否存在影响。或者使用相关WAF拦截
​application\config.php 

`
'default_filter'         => 'htmlspecialchars,addslashes,strip_tags',
`
