### ISSUE TITLE
监听setTrigger 应该加一个清除控制

### ISSUE THREAD

**Issue by XinJiangQingMang** [caiweiming/DolphinPHP#8]
有的时候 切换显示隐藏并不需要清空隐藏的表单值，

 /**
     * 设置触发
     * @param string $trigger 需要触发的表单项名，目前支持select（单选类型）、text、radio三种
     * @param string $values 触发的值
     * @param string $show 触发后要显示的表单项名，目前不支持普通联动、范围、拖动排序、静态文本
     * @param bool   $is_clear 是否清除隐藏表单的值，默认清除
     * @author 蔡伟明 
     * @return $this
     */
    public function setTrigger($trigger = '', $values = '', $show = '', $is_clear = true)

**Comment by caiweiming** [comment]
好的，感谢您的建议！
